name: Python Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          pip install pylint flake8 mypy
          pip install -r requirements.txt  # Установить зависимости проекта

      - name: Run pylint
        run: pylint ./ --fail-under=8.0 

      - name: Run flake8
        run: flake8 ./ --max-line-length=100 --count --show-source --statistics

      - name: Run mypy
        run: mypy ./ --ignore-missing-imports
